DISPLAY_SIDE_SIZE = 600
DIM_SIDE_SIZE = 500
DIM_SIDE_HALF_SIZE = DIM_SIDE_SIZE // 2
CELL_WIDTH = 1.2

MAX_SPEED_ARROW_LENGTH = 50
MAX_ACCELERATION_ARROW_LENGTH = 50
MIN_DRAW_LENGTH = 10
CELL_RADIUS = 5
