DISPLAY_SIDE_SIZE = 900
DIM_SIDE_SIZE = 1000 # 450
DIM_SIDE_HALF_SIZE = DIM_SIDE_SIZE // 2
CELL_WIDTH = DISPLAY_SIDE_SIZE / DIM_SIDE_SIZE

MAX_SPEED_ARROW_LENGTH = 50
MAX_ACCELERATION_ARROW_LENGTH = 50
MIN_DRAW_LENGTH = 10
CELL_RADIUS = 2.5

SHIELD_RADIUS = 10
MAX_SHIELD_DURATION = 5000
ATTACK_CD = 5000
