DISPLAY_SIDE_SIZE = 600
DIM_SIDE_SIZE = 300
DIM_SIDE_HALF_SIZE = DIM_SIDE_SIZE // 2
CELL_WIDTH = DISPLAY_SIDE_SIZE // DIM_SIDE_SIZE

MAX_SPEED_ARROW_LENGTH = 50
MAX_ACCELERATION_ARROW_LENGTH = 50
MIN_DRAW_LENGTH = 10
CELL_RADIUS = 2.5
